swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
# use this to configure a traditional SMTP server
    MAILER_URL=smtp://localhost:465?encryption=ssl&auth_mode=login&username=&password=