#default_index:
  # path: /
  #controller: App\Controller\DefaultController::index

boutique:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /boutique
    permanent: true